//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenMenuEditorWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenMenuEditorWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;omf uuid=&quot;df8cb20e-297c-11e0-91d7-0018512e6b26&quot; date_created=&quot;2011-01-27&quot;&gt;
        ///  &lt;menus&gt;
        ///    &lt;menu name=&quot;a la carte&quot; currency_symbol=&quot;EUR&quot; uid=&quot;1&quot;&gt;
        ///      &lt;menu_description&gt;&lt;/menu_description&gt;
        ///      &lt;menu_duration&gt;
        ///        &lt;menu_duration_name&gt;all&lt;/menu_duration_name&gt;
        ///        &lt;menu_duration_time_start&gt;&lt;/menu_duration_time_start&gt;
        ///        &lt;menu_duration_time_end&gt;&lt;/menu_duration_time_end&gt;
        ///      &lt;/menu_duration&gt;
        ///      &lt;menu_groups&gt;
        ///        &lt;menu_group name=&quot;Vorspeisen&quot; uid=&quot;1&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string alacarte_menu {
            get {
                return ResourceManager.GetString("alacarte_menu", resourceCulture);
            }
        }
    }
}
